/* Generated by Nim Compiler v1.2.0 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
    #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  struct Exception;
struct NimStrPayload;
struct NimStringV2;
struct TSafePoint;
struct GcFrameHeader;
struct tyObject_RangeError__8inKGns6i1OoXN9aLZwcSOw;
struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA;
struct RootObj;
struct TNimType;
struct tySequence__uB9b75OUPRENsBAu4AnoePA;
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
struct tyObject_OverflowError__Ss6DFlX5iSZpHRZDmP74bg;
struct tyObject_ArithmeticError__XIT9aewsXycM2U5B437NUDA;
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
struct tyObject_DivByZeroError__vASt1Zy2CLWqyBeLxcXqow;
struct tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw;
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct tyObject_NimSeqV2__A9aaPj3Ay2mWlTU3QheYz2w;
struct tyObject_NimSeqPayload__T3NJfV3Yh9bN9cuVRNI5QtfQ;
struct tyObject_NilAccessError__GOcOTSJVFwA9bjh66gBCclQ;
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9axCnCRMUx32AHzFgBrzSMg) (Exception* e);
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef N_NIMCALL_PTR(void, tyProc__NFmM6mqUOVW3cJg4yvk8Fw) (Exception* e);
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef N_NIMCALL_PTR(void, tyProc__W6IXMh2CA4X1rFYGjUb4yg) (NimStringV2 msg);
typedef TFrame* tyArray__pFdcUVk36Xt0LD9bLg3YaIQ[128];
struct TNimType {
void* destructor;
NI size;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
};
struct RootObj {
TNimType* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception : public RootObj {
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA : public Exception {
};
struct tyObject_RangeError__8inKGns6i1OoXN9aLZwcSOw : public tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA {
};
struct tyObject_ArithmeticError__XIT9aewsXycM2U5B437NUDA : public tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA {
};
struct tyObject_OverflowError__Ss6DFlX5iSZpHRZDmP74bg : public tyObject_ArithmeticError__XIT9aewsXycM2U5B437NUDA {
};
struct tyObject_DivByZeroError__vASt1Zy2CLWqyBeLxcXqow : public tyObject_ArithmeticError__XIT9aewsXycM2U5B437NUDA {
};
typedef N_NIMCALL_PTR(void, tyProc__4SVlZZPmetqBimNsH9cHcOA) (void* p);
struct tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw {
NI cap;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_NimSeqV2__A9aaPj3Ay2mWlTU3QheYz2w {
NI len;
tyObject_NimSeqPayload__T3NJfV3Yh9bN9cuVRNI5QtfQ* p;
};
struct tyObject_NimSeqPayload__T3NJfV3Yh9bN9cuVRNI5QtfQ {
NI cap;
tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
struct tyObject_NilAccessError__GOcOTSJVFwA9bjh66gBCclQ : public tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA {
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      static N_INLINE(void, initStackBottom)(void);
static N_INLINE(void, sysFatal__UO7gyScsaKQMHY4DQ3daHgsystem)(NimStringV2 message);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, sysFatal__1rw9bzpRcCrBi6FIqHe7a4wsystem)(NimStringV2 message);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___SJcVq9aHUKEeQF6mKDkE6pw)(tyObject_OverflowError__Ss6DFlX5iSZpHRZDmP74bg& dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
N_LIB_PRIVATE N_NIMCALL(void, writeStackTrace__amVlU9ajqZ06ujoesRBHcDg)(void);
N_LIB_PRIVATE N_NIMCALL(void, rawWriteStackTrace__LYPY2vdF8PVrf1RSKEqgkA)(NimStringV2& s);
static N_INLINE(void, appendString)(NimStringV2& dest, NimStringV2 src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2& s, NI addlen);
N_LIB_PRIVATE N_NOCONV(void*, allocShared0Impl__1Sx5YIRdVWZ4weqfKjYzWA)(NI size);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__1Sx5YIRdVWZ4weqfKjYzWA_2)(NI size);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, resize__cOCDWr16YD4j3dBrbbH3yQsystem)(NI old);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res);
static N_INLINE(NF, toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem)(NI i);
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(void, sysFatal__7P7hBAiMYMVi3v9alSlXmSwsystem)(NimStringV2 message);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___CiaBzGuSuzPVhX0vLVmlsg)(tyObject_DivByZeroError__vASt1Zy2CLWqyBeLxcXqow& dest);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2& dest);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p);
N_LIB_PRIVATE N_NOCONV(void, deallocSharedImpl__lmwgHsdhTsrQaepFju8wew)(void* p);
N_LIB_PRIVATE N_NOCONV(void, deallocImpl__lmwgHsdhTsrQaepFju8wew_2)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___4fQQqvAqifkWGVa4g39cI5A)(tySequence__uB9b75OUPRENsBAu4AnoePA& dest);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, rawWriteStackTrace__zo0sKsXK7oXYz0ERc41mPw)(tySequence__uB9b75OUPRENsBAu4AnoePA& s);
N_LIB_PRIVATE N_NIMCALL(void, auxWriteStackTrace__cEBhPS13dF9bIXoO5ipUApw)(TFrame* f, tySequence__uB9b75OUPRENsBAu4AnoePA& s);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___IbiBQ3RaksCQ9bs4LD5zMig)(tySequence__uB9b75OUPRENsBAu4AnoePA& dest, tySequence__uB9b75OUPRENsBAu4AnoePA src);
N_LIB_PRIVATE N_NIMCALL(tySequence__uB9b75OUPRENsBAu4AnoePA, newSeq__0du5Us2v5bU6GIaJAPx4mw)(NI len);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize);
N_LIB_PRIVATE N_NIMCALL(void, setLen__eCckgeg9cwKSQ79b13nmCLbA)(tySequence__uB9b75OUPRENsBAu4AnoePA& s, NI newlen);
N_LIB_PRIVATE N_NIMCALL(void, shrink__jisrtrsNMs8YrFrDOzCI6Q)(tySequence__uB9b75OUPRENsBAu4AnoePA& x, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void*, prepareSeqAdd__11KnDEqKYfU1F7UoiSyJcA)(NI len, void* p, NI addlen, NI elemSize);
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y);
N_LIB_PRIVATE N_NOCONV(void*, reallocShared0Impl__VpSzPpcaA5o3lCb27iz7xA)(void* p, NI oldSize, NI newSize);
N_LIB_PRIVATE N_NOCONV(void*, realloc0Impl__VpSzPpcaA5o3lCb27iz7xA_2)(void* p, NI oldSize, NI newSize);
N_LIB_PRIVATE N_NOCONV(void*, reallocImpl__XYb75pepKTKtzv9abwjURxA)(void* p, NI newSize);
static N_INLINE(void, zeroMem__9cLyRtoQz0YlIMEd4qW7Hdgsystem)(void* p, NI size);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NIMCALL(void, add__VHIeeMfqavFfKtbV1Wal0Q)(tySequence__uB9b75OUPRENsBAu4AnoePA& x, tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA value);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionAux__na8C8pUZ9cLQWVwk35l5vfw)(Exception* e);
static N_INLINE(void, pushCurrentException)(Exception* e);
N_LIB_PRIVATE N_NIMCALL(void, eq___rR9boD7urcxl7uyUtE46AOA)(Exception*& dest, Exception* src);
static N_INLINE(void, nimIncRef)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___rR9boD7urcxl7uyUtE46AOA_2)(Exception*& dest, Exception* src);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NIMCALL(void, auxWriteStackTrace__CxE7ORPNkX9cb5SNfDQ2yPQ)(TFrame* f, NimStringV2& s);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2& dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIntToStr)(NI x);
N_LIB_PRIVATE N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(void, sysFatal__rmMwjwTwcnO3nfuGk3FZeAsystem)(NimStringV2 message);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___sS6ejz4UvAmG5PeEn1axqQ)(tyObject_NilAccessError__GOcOTSJVFwA9bjh66gBCclQ& dest);
N_NIMCALL(NimStringV2, rawNewString)(NI cap);
N_LIB_PRIVATE N_NIMCALL(void, addInt__mftMOxbyu0h4yByfs3sqjA)(NimStringV2& result, NI64 x);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2& s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationV2)(NimStringV2& s);
N_LIB_PRIVATE N_NIMCALL(void, add__8FwY5enLGB0dFerO6Ny9caw)(NimStringV2& x, NCSTRING y);
N_LIB_PRIVATE N_NIMCALL(void, nimAddCharV1)(NimStringV2& s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, showErrorMessage__zsORN9crdKxsL9cHrQcdHSMw)(NCSTRING data);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toNimStr)(NCSTRING str, NI len);
static N_INLINE(size_t, nimCStrLen)(NCSTRING a);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, writeToStdErr__a2kDfqdSc1eYf0ZCWOGinQ)(NCSTRING msg);
static N_INLINE(void, rawWrite)(FILE* f, NCSTRING s);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___p2qOs6FbMz4AMrZbQK62BQ)(tyObject_RangeError__8inKGns6i1OoXN9aLZwcSOw& dest);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimInt64ToStr)(NI64 x);
N_LIB_PRIVATE N_NIMCALL(void, reportUnhandledError__na8C8pUZ9cLQWVwk35l5vfw_2)(Exception* e);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE TNimType NTI__Ss6DFlX5iSZpHRZDmP74bg_;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_3 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_4 = {0, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_3};
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_5 = { 29 | NIM_STRLIT_FLAG, "No stack traceback available\012" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_6 = {29, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_5};
N_LIB_PRIVATE TNimType NTI__vASt1Zy2CLWqyBeLxcXqow_;
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_32 = { 16 | NIM_STRLIT_FLAG, "division by zero" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_33 = {16, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_32};
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_39 = { 34 | NIM_STRLIT_FLAG, "Traceback (most recent call last)\012" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_40 = {34, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_39};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_41 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_42 = {1, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_41};
N_LIB_PRIVATE TNimType NTI__GOcOTSJVFwA9bjh66gBCclQ_;
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_43 = { 33 | NIM_STRLIT_FLAG, "attempt to write to a nil address" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_44 = {33, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_43};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_51 = { 20 | NIM_STRLIT_FLAG, " calls omitted) ...\012" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_52 = {20, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_51};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_55 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_56 = {1, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_55};
static const struct {
  NI cap; NIM_CHAR data[50+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_59 = { 50 | NIM_STRLIT_FLAG, "Error: call depth limit reached in a debug build (" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_60 = {50, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_59};
static const struct {
  NI cap; NIM_CHAR data[117+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_61 = { 117 | NIM_STRLIT_FLAG, " function calls). You can change it with -d:nimCallDepthLimit=<"
"int> but really try to avoid deep recursions instead.\012" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_62 = {117, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_61};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_64 = { 18 | NIM_STRLIT_FLAG, "over- or underflow" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_65 = {18, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_64};
N_LIB_PRIVATE TNimType NTI__8inKGns6i1OoXN9aLZwcSOw_;
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_66 = { 20 | NIM_STRLIT_FLAG, "value out of range: " };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_67 = {20, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_66};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_68 = { 7 | NIM_STRLIT_FLAG, " notin " };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_69 = {7, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_68};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_70 = { 4 | NIM_STRLIT_FLAG, " .. " };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_71 = {4, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_70};
N_LIB_PRIVATE NI nim_program_result;
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg globalRaiseHook__JbO1ti4ULxrw54m4zNPbpA;
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg localRaiseHook__EIvMhANBvB9cp2Ezvt29cADg;
N_LIB_PRIVATE tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ outOfMemHook__kZNaA7u1MfSW5ZeoGvw8xg;
N_LIB_PRIVATE tyProc__NFmM6mqUOVW3cJg4yvk8Fw unhandledExceptionHook__RJpSsXsRUH8ochbXTEhRIw;
N_LIB_PRIVATE Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
N_LIB_PRIVATE tyProc__W6IXMh2CA4X1rFYGjUb4yg errorMessageWriter__ZXnv0JyrWe3HTd07wpSr7A;
N_LIB_PRIVATE TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
N_LIB_PRIVATE TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
N_LIB_PRIVATE GcFrameHeader* gcFramePtr__ot48iojqko9aFxGhyjjjVaA;
N_LIB_PRIVATE tyArray__pFdcUVk36Xt0LD9bLg3YaIQ tempFrames__7nBYIr2UsDREpYylZK4fug;
N_LIB_PRIVATE tyProc__W6IXMh2CA4X1rFYGjUb4yg onUnhandledException__bFrawQlTKZhLweDD36j9b8g;
N_LIB_PRIVATE NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
static N_INLINE(void, initStackBottom)(void) {
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU32)(((NU) (a))) + (NU32)(((NU) (b))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(r ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(r ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
{		(*res) = r;
}	}
	goto LA1_;
	LA5_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringV2& dest, NimStringV2 src) {
{	{
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_7;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_8;
		if (!(((NI) 0) < src.len)) goto LA3_;
{		if (nimAddInt(src.len, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_7)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_7)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_7)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_7), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*dest.p).data[dest.len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_7))));
		if (nimAddInt(dest.len, src.len, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_8)) { raiseOverflow(); goto BeforeRet_;
};
		dest.len = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_8);
}	}
	LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__1Sx5YIRdVWZ4weqfKjYzWA_2)(NI size) {
	void* result;
	nimfr_("alloc0Impl", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	result = (void*)0;
	nimln_(6, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	result = calloc(((size_t) (size)), ((size_t) 1));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NOCONV(void*, allocShared0Impl__1Sx5YIRdVWZ4weqfKjYzWA)(NI size) {
	void* result;
	nimfr_("allocShared0Impl", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	result = (void*)0;
	nimln_(26, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	result = alloc0Impl__1Sx5YIRdVWZ4weqfKjYzWA_2(size);
	popFrame();
	return result;
}
static N_INLINE(NF, toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem)(NI i) {
	NF result;
	nimfr_("toFloat", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system.nim");
	result = (NF)0;
	nimln_(1372, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system.nim");
	result = ((NF) (i));
	popFrame();
	return result;
}
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x) {
	NF result;
	result = (NF)0;
	{
		if (!(x < 0.0)) goto LA3_;
{		result = -(x);
}	}
	goto LA1_;
	LA3_: ;
	{
		result = x;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU32)(((NU) (a))) * (NU32)(((NU) (b))))));
	NF T1_ = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(a);
	NF T2_ = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(b);
	NF floatProd = ((NF)(T1_) * (NF)(T2_));
	NF T3_ = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(r);
	NF resAsFloat = T3_;
	{
		if (!(resAsFloat == floatProd)) goto LA6_;
{		(*res) = r;
}	}
	goto LA4_;
	LA6_: ;
	{
		{
			NF T11_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(((NF)(resAsFloat) - (NF)(floatProd)));
			NF T12_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(floatProd);
			if (!(((NF)(3.2000000000000000e+01) * (NF)(T11_)) <= T12_)) goto LA13_;
{			(*res) = r;
}		}
		goto LA9_;
		LA13_: ;
		{
			result = NIM_TRUE;
		}
		LA9_: ;
	}
	LA4_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p) {
	nimfr_("nimRawDispose", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	nimln_(109, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	nimln_(52, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	NI T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 4));
	nimln_(109, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	free(((void*) (T1_)));
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p) {
NIM_BOOL* nimErr_;
	nimfr_("nimDestroyAndDispose", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
{nimErr_ = nimErrorFlag();
	nimln_(119, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	void* d = (*(*((TNimType**) (p)))).destructor;
	nimln_(120, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	{
		if (!!((d == NIM_NIL))) goto LA3_;
{		((tyProc__4SVlZZPmetqBimNsH9cHcOA) (d))(p);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
}	}
	LA3_: ;
	nimln_(128, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	nimRawDispose(p);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NOCONV(void, deallocImpl__lmwgHsdhTsrQaepFju8wew_2)(void* p) {
	nimfr_("deallocImpl", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	nimln_(17, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	free(p);
	popFrame();
}
N_LIB_PRIVATE N_NOCONV(void, deallocSharedImpl__lmwgHsdhTsrQaepFju8wew)(void* p) {
	nimfr_("deallocSharedImpl", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	nimln_(34, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	deallocImpl__lmwgHsdhTsrQaepFju8wew_2(p);
	popFrame();
}
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p) {
	deallocSharedImpl__lmwgHsdhTsrQaepFju8wew(p);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2& dest) {
	if (dest.p && !(dest.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest.p);
 dest.p = NIM_NIL; dest.len = 0; }
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___4fQQqvAqifkWGVa4g39cI5A)(tySequence__uB9b75OUPRENsBAu4AnoePA& dest) {
	NI colontmp_ = ((NI) 0);
	{
		while (1) {
			NI T3_;
			T3_ = dest.len;
			if (!(colontmp_ < T3_)) goto LA2;
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
	if (dest.p && !(dest.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest.p);
 dest.p = NIM_NIL; dest.len = 0; }
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___CiaBzGuSuzPVhX0vLVmlsg)(tyObject_DivByZeroError__vASt1Zy2CLWqyBeLxcXqow& dest) {
	{
		NIM_BOOL T3_ = nimDecRefIsLast(dest.parent);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest.parent);
		dest.parent = NIM_NIL;
}	}
	LA4_: ;
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(dest.message);
	eqdestroy___4fQQqvAqifkWGVa4g39cI5A(dest.trace);
	{
		NIM_BOOL T8_ = nimDecRefIsLast(dest.up);
		if (!T8_) goto LA9_;
{		nimDestroyAndDispose(dest.up);
		dest.up = NIM_NIL;
}	}
	LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___IbiBQ3RaksCQ9bs4LD5zMig)(tySequence__uB9b75OUPRENsBAu4AnoePA& dest, tySequence__uB9b75OUPRENsBAu4AnoePA src) {
	if (dest.len && dest.p != src.p) {	eqdestroy___4fQQqvAqifkWGVa4g39cI5A(dest);
	}
dest.len = src.len; dest.p = src.p;
}
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize) {
	void* result;
{	result = (void*)0;
	{
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_17;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_18;
		if (!(((NI) 0) < cap)) goto LA3_;
{		if (nimMulInt(cap, elemSize, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_17)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_17), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_18)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_18)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_18)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_18), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		void* T5_ = allocShared0Impl__1Sx5YIRdVWZ4weqfKjYzWA(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_18))));
		tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw* p = ((tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw*) (T5_));
		(*p).cap = cap;
		result = ((void*) (p));
}	}
	goto LA1_;
	LA3_: ;
	{
		result = NIM_NIL;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__uB9b75OUPRENsBAu4AnoePA, newSeq__0du5Us2v5bU6GIaJAPx4mw)(NI len) {
	tySequence__uB9b75OUPRENsBAu4AnoePA result;
	nimfr_("newSeq", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system.nim");
	result.len = 0; result.p = NIM_NIL;
	nimln_(643, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system.nim");
	result.len = len; result.p = (tySequence__uB9b75OUPRENsBAu4AnoePA_Content*) newSeqPayload(len, sizeof(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, shrink__jisrtrsNMs8YrFrDOzCI6Q)(tySequence__uB9b75OUPRENsBAu4AnoePA& x, NI newLen) {
	(*((tyObject_NimSeqV2__A9aaPj3Ay2mWlTU3QheYz2w*) ((&x)))).len = ((NI) (newLen));
}
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y) {
	NI result;
	nimfr_("+%", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/arithmetics."
"nim");
	result = (NI)0;
	nimln_(426, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/arithmetics."
"nim");
	nimln_(430, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/arithmetics."
"nim");
	result = ((NI) ((NU)((NU32)(((NU) (x))) + (NU32)(((NU) (y))))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NOCONV(void*, reallocImpl__XYb75pepKTKtzv9abwjURxA)(void* p, NI newSize) {
	void* result;
	nimfr_("reallocImpl", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	result = (void*)0;
	nimln_(9, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	result = realloc(p, ((size_t) (newSize)));
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {
	void* T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, zeroMem__9cLyRtoQz0YlIMEd4qW7Hdgsystem)(void* p, NI size) {
	nimZeroMem(p, size);
}
N_LIB_PRIVATE N_NOCONV(void*, realloc0Impl__VpSzPpcaA5o3lCb27iz7xA_2)(void* p, NI oldSize, NI newSize) {
	void* result;
	nimfr_("realloc0Impl", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	result = (void*)0;
	nimln_(12, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	result = reallocImpl__XYb75pepKTKtzv9abwjURxA(p, ((NI) (((size_t) (newSize)))));
	nimln_(13, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	{
		if (!(((NI) (oldSize)) < ((NI) (newSize)))) goto LA3_;
{		nimln_(14, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
		zeroMem__9cLyRtoQz0YlIMEd4qW7Hdgsystem(((void*) ((NI)(((NI) (ptrdiff_t) (result)) + ((NI) (oldSize))))), ((NI) ((NI)(((NI) (newSize)) - ((NI) (oldSize))))));
}	}
	LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NOCONV(void*, reallocShared0Impl__VpSzPpcaA5o3lCb27iz7xA)(void* p, NI oldSize, NI newSize) {
	void* result;
	nimfr_("reallocShared0Impl", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	result = (void*)0;
	nimln_(32, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/mm/malloc.ni"
"m");
	result = realloc0Impl__VpSzPpcaA5o3lCb27iz7xA_2(p, oldSize, newSize);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, prepareSeqAdd__11KnDEqKYfU1F7UoiSyJcA)(NI len, void* p, NI addlen, NI elemSize) {
	void* result;
{	result = (void*)0;
	{
		if (!(addlen <= ((NI) 0))) goto LA3_;
{		result = p;
}	}
	goto LA1_;
	LA3_: ;
	{
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_19;
		if (!(p == NIM_NIL)) goto LA6_;
{		if (nimAddInt(len, addlen, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_19)) { raiseOverflow(); goto BeforeRet_;
};
		result = newSeqPayload((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_19), elemSize);
}	}
	goto LA1_;
	LA6_: ;
	{
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_20;
		tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw* p_2 = ((tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw*) (p));
		NI oldCap = (NI)((*p_2).cap & ((NI) -1073741825));
		NI T9_ = resize__cOCDWr16YD4j3dBrbbH3yQsystem(oldCap);
		if (nimAddInt(len, addlen, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_20)) { raiseOverflow(); goto BeforeRet_;
};
		NI newCap = ((T9_ >= (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_20)) ? T9_ : (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_20));
		{
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_21;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_22;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_23;
			if (!((NI)((*p_2).cap & ((NI) 1073741824)) == ((NI) 1073741824))) goto LA12_;
{			if (nimMulInt(elemSize, newCap, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_21)) { raiseOverflow(); goto BeforeRet_;
};
			if (nimAddInt(((NI) 4), (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_21), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_22)) { raiseOverflow(); goto BeforeRet_;
};
			if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_22)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_22)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_22), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			void* T14_ = allocShared0Impl__1Sx5YIRdVWZ4weqfKjYzWA(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_22))));
			tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw* q = ((tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw*) (T14_));
			NI T15_ = pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (q)), ((NI) 4));
			NI T16_ = pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (p_2)), ((NI) 4));
			if (nimMulInt(len, elemSize, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_23)) { raiseOverflow(); goto BeforeRet_;
};
			if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_23)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_23)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_23), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) (T15_)), ((void*) (T16_)), ((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_23))));
			(*q).cap = newCap;
			result = ((void*) (q));
}		}
		goto LA10_;
		LA12_: ;
		{
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_24;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_25;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_26;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_27;
			if (nimMulInt(elemSize, oldCap, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_24)) { raiseOverflow(); goto BeforeRet_;
};
			if (nimAddInt(((NI) 4), (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_24), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_25)) { raiseOverflow(); goto BeforeRet_;
};
			NI oldSize = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_25);
			if (nimMulInt(elemSize, newCap, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_26)) { raiseOverflow(); goto BeforeRet_;
};
			if (nimAddInt(((NI) 4), (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_26), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_27)) { raiseOverflow(); goto BeforeRet_;
};
			NI newSize = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_27);
			if ((oldSize) < ((NI) 0) || (oldSize) > ((NI) 2147483647)){ raiseRangeErrorI(oldSize, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			if ((newSize) < ((NI) 0) || (newSize) > ((NI) 2147483647)){ raiseRangeErrorI(newSize, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			void* T18_ = reallocShared0Impl__VpSzPpcaA5o3lCb27iz7xA(((void*) (p_2)), ((NI) (oldSize)), ((NI) (newSize)));
			tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw* q_2 = ((tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw*) (T18_));
			(*q_2).cap = newCap;
			result = ((void*) (q_2));
		}
		LA10_: ;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU32)(((NU) (a))) - (NU32)(((NU) (b))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(r ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU32) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
{		(*res) = r;
}	}
	goto LA1_;
	LA5_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setLen__eCckgeg9cwKSQ79b13nmCLbA)(tySequence__uB9b75OUPRENsBAu4AnoePA& s, NI newlen) {
{	{
		NI T3_;
		T3_ = s.len;
		if (!(((NI) (newlen)) < T3_)) goto LA4_;
{		shrink__jisrtrsNMs8YrFrDOzCI6Q(s, newlen);
}	}
	goto LA1_;
	LA4_: ;
	{
		NI T7_;
		T7_ = s.len;
		NI oldLen = T7_;
		{
			if (!(((NI) (newlen)) <= oldLen)) goto LA10_;
{			goto BeforeRet_;
}		}
		LA10_: ;
		tyObject_NimSeqV2__A9aaPj3Ay2mWlTU3QheYz2w* xu = ((tyObject_NimSeqV2__A9aaPj3Ay2mWlTU3QheYz2w*) ((&s)));
		{
			NIM_BOOL T14_;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_28;
			T14_ = (NIM_BOOL)0;
			T14_ = ((*xu).p == NIM_NIL);
			if (T14_) goto LA15_;
			T14_ = ((*(*xu).p).cap < ((NI) (newlen)));
			LA15_: ;
			if (!T14_) goto LA16_;
{			if (nimSubInt(((NI) (newlen)), oldLen, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_28)) { raiseOverflow(); goto BeforeRet_;
};
			void* T18_ = prepareSeqAdd__11KnDEqKYfU1F7UoiSyJcA(oldLen, ((void*) ((*xu).p)), (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_28), ((NI) 12));
			(*xu).p = ((tyObject_NimSeqPayload__T3NJfV3Yh9bN9cuVRNI5QtfQ*) (T18_));
}		}
		LA16_: ;
		(*xu).len = ((NI) (newlen));
	}
	LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, auxWriteStackTrace__cEBhPS13dF9bIXoO5ipUApw)(TFrame* f, tySequence__uB9b75OUPRENsBAu4AnoePA& s) {
	NCSTRING colontmpD_;
	NI colontmpD__2;
	NCSTRING colontmpD__3;
	colontmpD_ = (NCSTRING)0;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NCSTRING)0;
	TFrame* it = f;
	NI i = ((NI) 0);
	{
		while (1) {
			if (!!((it == NIM_NIL))) goto LA2;
			i += ((NI) 1);
			it = (*it).prev;
		} LA2: ;
	}
	NI last = (NI)(i - ((NI) 1));
	{
		NI T5_;
		T5_ = s.len;
		if (!(T5_ == ((NI) 0))) goto LA6_;
{		tySequence__uB9b75OUPRENsBAu4AnoePA T8_ = newSeq__0du5Us2v5bU6GIaJAPx4mw(((NI) (i)));
		eqsink___IbiBQ3RaksCQ9bs4LD5zMig(s, T8_);
}	}
	goto LA3_;
	LA6_: ;
	{
		NI T10_;
		T10_ = s.len;
		last = (NI)((NI)(T10_ + i) - ((NI) 1));
		setLen__eCckgeg9cwKSQ79b13nmCLbA(s, ((NI) ((NI)(last + ((NI) 1)))));
	}
	LA3_: ;
	it = f;
	{
		while (1) {
			tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA T13_;
			if (!!((it == NIM_NIL))) goto LA12;
			nimZeroMem((void*)(&T13_), sizeof(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA));
			colontmpD_ = (*it).procname;
			T13_.procname = colontmpD_;
			colontmpD__2 = (*it).line;
			T13_.line = colontmpD__2;
			colontmpD__3 = (*it).filename;
			T13_.filename = colontmpD__3;
			s.p->data[last] = T13_;
			it = (*it).prev;
			last -= ((NI) 1);
		} LA12: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, rawWriteStackTrace__zo0sKsXK7oXYz0ERc41mPw)(tySequence__uB9b75OUPRENsBAu4AnoePA& s) {
	auxWriteStackTrace__cEBhPS13dF9bIXoO5ipUApw(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw, s);
}
N_LIB_PRIVATE N_NIMCALL(void, add__VHIeeMfqavFfKtbV1Wal0Q)(tySequence__uB9b75OUPRENsBAu4AnoePA& x, tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA value) {
	NI T1_;
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_30;
{	T1_ = x.len;
	NI oldLen = T1_;
	tyObject_NimSeqV2__A9aaPj3Ay2mWlTU3QheYz2w* xu = ((tyObject_NimSeqV2__A9aaPj3Ay2mWlTU3QheYz2w*) ((&x)));
	{
		NIM_BOOL T4_;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_29;
		T4_ = (NIM_BOOL)0;
		T4_ = ((*xu).p == NIM_NIL);
		if (T4_) goto LA5_;
		if (nimAddInt(oldLen, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_29)) { raiseOverflow(); goto BeforeRet_;
};
		T4_ = ((*(*xu).p).cap < (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_29));
		LA5_: ;
		if (!T4_) goto LA6_;
{		void* T8_ = prepareSeqAdd__11KnDEqKYfU1F7UoiSyJcA(oldLen, ((void*) ((*xu).p)), ((NI) 1), ((NI) 12));
		(*xu).p = ((tyObject_NimSeqPayload__T3NJfV3Yh9bN9cuVRNI5QtfQ*) (T8_));
}	}
	LA6_: ;
	if (nimAddInt(oldLen, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_30)) { raiseOverflow(); goto BeforeRet_;
};
	(*xu).len = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_30);
	(*(*xu).p).data[oldLen] = value;
	}BeforeRet_: ;
}
static N_INLINE(void, nimIncRef)(void* p) {
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_31;
	nimfr_("nimIncRef", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
{	nimln_(96, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	nimln_(55, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	NI T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 4));
	if (nimAddInt((*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_))).rc, ((NI) 8), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_31)) { raiseOverflow(); goto BeforeRet_;
};
	(*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_))).rc = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_31);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eq___rR9boD7urcxl7uyUtE46AOA)(Exception*& dest, Exception* src) {
	{
		if (!src) goto LA3_;
{		nimIncRef(src);
}	}
	LA3_: ;
	{
		NIM_BOOL T7_ = nimDecRefIsLast(dest);
		if (!T7_) goto LA8_;
{		nimDestroyAndDispose(dest);
}	}
	LA8_: ;
	dest = src;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___rR9boD7urcxl7uyUtE46AOA_2)(Exception*& dest, Exception* src) {
	{
		NIM_BOOL T3_ = nimDecRefIsLast(dest);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest);
}	}
	LA4_: ;
	dest = src;
}
static N_INLINE(void, pushCurrentException)(Exception* e) {
	eq___rR9boD7urcxl7uyUtE46AOA((*e).up, currException__9bVPeDJlYTi9bQApZpfH8wjg);
	eqsink___rR9boD7urcxl7uyUtE46AOA_2(currException__9bVPeDJlYTi9bQApZpfH8wjg, e);
	e = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionAux__na8C8pUZ9cLQWVwk35l5vfw)(Exception* e) {
{	{
		if (!!((localRaiseHook__EIvMhANBvB9cp2Ezvt29cADg == NIM_NIL))) goto LA3_;
{		{
			NIM_BOOL T7_ = localRaiseHook__EIvMhANBvB9cp2Ezvt29cADg(e);
			if (!!(T7_)) goto LA8_;
{			goto BeforeRet_;
}		}
		LA8_: ;
}	}
	LA3_: ;
	{
		if (!!((globalRaiseHook__JbO1ti4ULxrw54m4zNPbpA == NIM_NIL))) goto LA12_;
{		{
			NIM_BOOL T16_ = globalRaiseHook__JbO1ti4ULxrw54m4zNPbpA(e);
			if (!!(T16_)) goto LA17_;
{			goto BeforeRet_;
}		}
		LA17_: ;
}	}
	LA12_: ;
	{
		if (!!((e == currException__9bVPeDJlYTi9bQApZpfH8wjg))) goto LA21_;
{		pushCurrentException(e);
}	}
	LA21_: ;
	nimInErrorMode__759bT87luu8XGcbkw13FUjA += ((NI) 1);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line) {
	{
		if (!((*e).name == 0)) goto LA3_;
{		(*e).name = ename;
}	}
	LA3_: ;
	{
		NI T7_;
		T7_ = (*e).trace.len;
		if (!(T7_ == ((NI) 0))) goto LA8_;
{		rawWriteStackTrace__zo0sKsXK7oXYz0ERc41mPw((*e).trace);
}	}
	goto LA5_;
	LA8_: ;
	{
		tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA T13_;
		tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA T14_;
		if (!!((framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL))) goto LA11_;
{		nimZeroMem((void*)(&T13_), sizeof(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA));
		T13_.procname = NIM_NIL;
		T13_.line = ((NI) -10);
		T13_.filename = NIM_NIL;
		add__VHIeeMfqavFfKtbV1Wal0Q((*e).trace, T13_);
		auxWriteStackTrace__cEBhPS13dF9bIXoO5ipUApw(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw, (*e).trace);
		nimZeroMem((void*)(&T14_), sizeof(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA));
		T14_.procname = NIM_NIL;
		T14_.line = ((NI) -100);
		T14_.filename = NIM_NIL;
		add__VHIeeMfqavFfKtbV1Wal0Q((*e).trace, T14_);
}	}
	goto LA5_;
	LA11_: ;
	LA5_: ;
	raiseExceptionAux__na8C8pUZ9cLQWVwk35l5vfw(e);
}
static N_INLINE(void, sysFatal__7P7hBAiMYMVi3v9alSlXmSwsystem)(NimStringV2 message) {
	tyObject_DivByZeroError__vASt1Zy2CLWqyBeLxcXqow* T2_;
	NimStringV2 blitTmp;
NIM_BOOL* nimErr_;
	nimfr_("sysFatal", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/fatal.nim");
{nimErr_ = nimErrorFlag();
	T2_ = (tyObject_DivByZeroError__vASt1Zy2CLWqyBeLxcXqow*)0;
	T2_ = (tyObject_DivByZeroError__vASt1Zy2CLWqyBeLxcXqow*) nimNewObj(sizeof(tyObject_DivByZeroError__vASt1Zy2CLWqyBeLxcXqow));
	(*T2_).m_type = (&NTI__vASt1Zy2CLWqyBeLxcXqow_);
	(*T2_).name = "DivByZeroError";
	nimln_(49, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/fatal.nim");
	blitTmp = message;
	message.len = 0; message.p = NIM_NIL;
	(*T2_).message = blitTmp;
	raiseExceptionEx((Exception*)T2_, "DivByZeroError", "sysFatal", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/fatal.nim", 49);
	goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(message);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	sysFatal__7P7hBAiMYMVi3v9alSlXmSwsystem(TM__Q5wkpxktOdTGvlSRo9bzt9aw_33);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a == ((NI) (-2147483647 -1)));
		if (!(T3_)) goto LA4_;
		T3_ = (b == ((NI) -1));
		LA4_: ;
		if (!T3_) goto LA5_;
{		result = NIM_TRUE;
}	}
	goto LA1_;
	LA5_: ;
	{
		(*res) = (NI)(a / b);
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, resize__cOCDWr16YD4j3dBrbbH3yQsystem)(NI old) {
	NI result;
{	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
{		result = ((NI) 4);
}	}
	goto LA1_;
	LA3_: ;
	{
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_15;
		if (!(old < ((NI) 65536))) goto LA6_;
{		if (nimMulInt(old, ((NI) 2), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_15)) { raiseOverflow(); goto BeforeRet_;
};
		result = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_15);
}	}
	goto LA1_;
	LA6_: ;
	{
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_16;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_34;
		if (nimMulInt(old, ((NI) 3), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_16)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI) 2) == 0){ raiseDivByZero(); goto BeforeRet_;
}
		if (nimDivInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_16), ((NI) 2), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_34)) { raiseOverflow(); goto BeforeRet_;
};
		result = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_34);
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2& s, NI addlen) {
{	{
		NIM_BOOL T3_;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_9;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_10;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_11;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_12;
		T3_ = (NIM_BOOL)0;
		T3_ = (s.p == NIM_NIL);
		if (T3_) goto LA4_;
		T3_ = ((NI)((*s.p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
		LA4_: ;
		if (!T3_) goto LA5_;
{		NimStrPayload* oldP = s.p;
		if (nimAddInt(s.len, addlen, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_9)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_9), ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_10)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_10), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_11)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_11)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_11)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_11), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		void* T7_ = allocShared0Impl__1Sx5YIRdVWZ4weqfKjYzWA(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_11))));
		s.p = ((NimStrPayload*) (T7_));
		if (nimAddInt(s.len, addlen, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_12)) { raiseOverflow(); goto BeforeRet_;
};
		(*s.p).cap = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_12);
		{
			if (!(((NI) 0) < s.len)) goto LA10_;
{			if ((s.len) < ((NI) 0) || (s.len) > ((NI) 2147483647)){ raiseRangeErrorI(s.len, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*s.p).data[((NI) 0)]))), ((void*) ((&(*oldP).data[((NI) 0)]))), ((NI) (s.len)));
}		}
		LA10_: ;
}	}
	goto LA1_;
	LA5_: ;
	{
		NI oldCap = (NI)((*s.p).cap & ((NI) -1073741825));
		{
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_13;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_14;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_35;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_36;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_37;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_38;
			if (nimAddInt(s.len, addlen, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_13)) { raiseOverflow(); goto BeforeRet_;
};
			if (!(oldCap < (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_13))) goto LA15_;
{			if (nimAddInt(s.len, addlen, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_14)) { raiseOverflow(); goto BeforeRet_;
};
			NI T17_ = resize__cOCDWr16YD4j3dBrbbH3yQsystem(oldCap);
			NI newCap = (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_14) >= T17_) ? (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_14) : T17_);
			if (nimAddInt(oldCap, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_35)) { raiseOverflow(); goto BeforeRet_;
};
			if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_35), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_36)) { raiseOverflow(); goto BeforeRet_;
};
			if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_36)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_36)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_36), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			if (nimAddInt(newCap, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_37)) { raiseOverflow(); goto BeforeRet_;
};
			if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_37), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_38)) { raiseOverflow(); goto BeforeRet_;
};
			if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_38)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_38)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_38), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			void* T18_ = reallocShared0Impl__VpSzPpcaA5o3lCb27iz7xA(((void*) (s.p)), ((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_36))), ((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_38))));
			s.p = ((NimStrPayload*) (T18_));
			(*s.p).cap = newCap;
}		}
		LA15_: ;
	}
	LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2& dest, NimStringV2 src) {
	if (dest.len && dest.p != src.p) {	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(dest);
	}
dest.len = src.len; dest.p = src.p;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___sS6ejz4UvAmG5PeEn1axqQ)(tyObject_NilAccessError__GOcOTSJVFwA9bjh66gBCclQ& dest) {
	{
		NIM_BOOL T3_ = nimDecRefIsLast(dest.parent);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest.parent);
		dest.parent = NIM_NIL;
}	}
	LA4_: ;
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(dest.message);
	eqdestroy___4fQQqvAqifkWGVa4g39cI5A(dest.trace);
	{
		NIM_BOOL T8_ = nimDecRefIsLast(dest.up);
		if (!T8_) goto LA9_;
{		nimDestroyAndDispose(dest.up);
		dest.up = NIM_NIL;
}	}
	LA9_: ;
}
static N_INLINE(void, sysFatal__rmMwjwTwcnO3nfuGk3FZeAsystem)(NimStringV2 message) {
	tyObject_NilAccessError__GOcOTSJVFwA9bjh66gBCclQ* T2_;
	NimStringV2 blitTmp;
NIM_BOOL* nimErr_;
	nimfr_("sysFatal", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/fatal.nim");
{nimErr_ = nimErrorFlag();
	T2_ = (tyObject_NilAccessError__GOcOTSJVFwA9bjh66gBCclQ*)0;
	T2_ = (tyObject_NilAccessError__GOcOTSJVFwA9bjh66gBCclQ*) nimNewObj(sizeof(tyObject_NilAccessError__GOcOTSJVFwA9bjh66gBCclQ));
	(*T2_).m_type = (&NTI__GOcOTSJVFwA9bjh66gBCclQ_);
	(*T2_).name = "NilAccessError";
	nimln_(49, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/fatal.nim");
	blitTmp = message;
	message.len = 0; message.p = NIM_NIL;
	(*T2_).message = blitTmp;
	raiseExceptionEx((Exception*)T2_, "NilAccessError", "sysFatal", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/fatal.nim", 49);
	goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(message);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NOINLINE(void, chckNil)(void* p) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(p == NIM_NIL)) goto LA3_;
{		sysFatal__rmMwjwTwcnO3nfuGk3FZeAsystem(TM__Q5wkpxktOdTGvlSRo9bzt9aw_44);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
}	}
	LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space) {
	NimStringV2 result;
{	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	{
		if (!(space <= ((NI) 0))) goto LA3_;
{		chckNil((void*)(&result));
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		result.p = NIM_NIL;
}	}
	goto LA1_;
	LA3_: ;
	{
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_45;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_46;
		if (nimAddInt(space, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_45)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_45), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_46)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_46)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_46)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_46), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		void* T6_ = allocShared0Impl__1Sx5YIRdVWZ4weqfKjYzWA(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_46))));
		NimStrPayload* p = ((NimStrPayload*) (T6_));
		(*p).cap = space;
		chckNil((void*)(&result));
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		result.p = p;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2& s, NI newLen) {
{	{
		if (!(newLen == ((NI) 0))) goto LA3_;
{		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = (s.p == NIM_NIL);
			if (T7_) goto LA8_;
			T7_ = ((NI)((*s.p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
			LA8_: ;
			if (!!(T7_)) goto LA9_;
{			deallocShared(((void*) (s.p)));
}		}
		LA9_: ;
		s.p = NIM_NIL;
}	}
	goto LA1_;
	LA3_: ;
	{
		{
			NIM_BOOL T14_;
			NIM_BOOL T16_;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_47;
			T14_ = (NIM_BOOL)0;
			T14_ = (s.len < newLen);
			if (T14_) goto LA15_;
			T16_ = (NIM_BOOL)0;
			T16_ = (s.p == NIM_NIL);
			if (T16_) goto LA17_;
			T16_ = ((NI)((*s.p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
			LA17_: ;
			T14_ = T16_;
			LA15_: ;
			if (!T14_) goto LA18_;
{			if (nimSubInt(newLen, s.len, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_47)) { raiseOverflow(); goto BeforeRet_;
};
			prepareAdd(s, (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_47));
}		}
		LA18_: ;
		(*s.p).data[newLen] = 0;
	}
	LA1_: ;
	s.len = newLen;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationV2)(NimStringV2& s) {
{	{
		NIM_BOOL T3_;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_48;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_49;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_50;
		T3_ = (NIM_BOOL)0;
		T3_ = !((s.p == NIM_NIL));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*s.p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
		LA4_: ;
		if (!T3_) goto LA5_;
{		NimStrPayload* oldP = s.p;
		if (nimAddInt(s.len, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_48)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_48), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_49)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_49)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_49)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_49), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		void* T7_ = allocShared0Impl__1Sx5YIRdVWZ4weqfKjYzWA(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_49))));
		s.p = ((NimStrPayload*) (T7_));
		(*s.p).cap = s.len;
		if (nimAddInt(s.len, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_50)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_50)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_50)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_50), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*s.p).data[((NI) 0)]))), ((void*) ((&(*oldP).data[((NI) 0)]))), ((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_50))));
}	}
	LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, addInt__mftMOxbyu0h4yByfs3sqjA)(NimStringV2& result, NI64 x) {
	nimfr_("addInt", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
	nimln_(51, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
	NI base = result.len;
	nimln_(52, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
	setLengthStrV2(result, ((NI) ((NI)(base + ((NI) 32)))));
	nimln_(53, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
	NI i = ((NI) 0);
	nimln_(54, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
	NI64 y = x;
	{
		nimln_(55, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
		while (1) {
			nimln_(56, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
			NI64 d = (NI64)(y / IL64(10));
			nimln_(57, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
			nimPrepareStrMutationV2(result);
			result.p->data[(NI)(base + i)] = ((NIM_CHAR) (((NI) ((NI)((((NI) ((NI64)(y - (NI64)(d * IL64(10))))) > 0? (((NI) ((NI64)(y - (NI64)(d * IL64(10)))))) : -(((NI) ((NI64)(y - (NI64)(d * IL64(10))))))) + ((NI) 48))))));
			nimln_(58, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
			i += ((NI) 1);
			nimln_(59, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
			y = d;
			nimln_(60, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
			{
				if (!(y == IL64(0))) goto LA5_;
{				goto LA1;
}			}
			LA5_: ;
		}
	} LA1: ;
	nimln_(61, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
	{
		if (!(x < IL64(0))) goto LA9_;
{		nimln_(62, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
		nimPrepareStrMutationV2(result);
		result.p->data[(NI)(base + i)] = 45;
		nimln_(63, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
		i += ((NI) 1);
}	}
	LA9_: ;
	nimln_(64, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
	setLengthStrV2(result, ((NI) ((NI)(base + i))));
	{
		NI j;
		NI colontmp_;
		j = (NI)0;
		colontmp_ = (NI)0;
		nimln_(66, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
		colontmp_ = (NI)((NI)(i / ((NI) 2)) - ((NI) 1));
		nimln_(77, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/iterators_1."
"nim");
		NI res = ((NI) 0);
		{
			nimln_(78, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/iterators_1."
"nim");
			while (1) {
				NIM_CHAR T14_;
				if (!(res <= colontmp_)) goto LA13;
				nimln_(66, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
				j = res;
				nimln_(67, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
				T14_ = (NIM_CHAR)0;
				T14_ = result.p->data[(NI)(base + j)];
				result.p->data[(NI)(base + j)] = result.p->data[(NI)((NI)((NI)(base + i) - j) - ((NI) 1))];
				result.p->data[(NI)((NI)((NI)(base + i) - j) - ((NI) 1))] = T14_;
				nimln_(80, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/iterators_1."
"nim");
				res += ((NI) 1);
			} LA13: ;
		}
	}
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIntToStr)(NI x) {
	NimStringV2 result;
	nimfr_("nimIntToStr", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
	result.len = 0; result.p = NIM_NIL;
	nimln_(74, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
	result = rawNewString(((NI) 16));
	nimln_(75, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
	addInt__mftMOxbyu0h4yByfs3sqjA(result, ((NI64) (x)));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nimAddCharV1)(NimStringV2& s, NIM_CHAR c) {
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_53;
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_54;
{	prepareAdd(s, ((NI) 1));
	(*s.p).data[s.len] = c;
	if (nimAddInt(s.len, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_53)) { raiseOverflow(); goto BeforeRet_;
};
	(*s.p).data[(NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_53)] = 0;
	if (nimAddInt(s.len, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_54)) { raiseOverflow(); goto BeforeRet_;
};
	s.len = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_54);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, add__8FwY5enLGB0dFerO6Ny9caw)(NimStringV2& x, NCSTRING y) {
	NI i = ((NI) 0);
	{
		if (!!((((void*) (y)) == NIM_NIL))) goto LA3_;
{		{
			while (1) {
				if (!!(((NU8)(y[i]) == (NU8)(0)))) goto LA6;
				nimAddCharV1(x, y[i]);
				i += ((NI) 1);
			} LA6: ;
		}
}	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, auxWriteStackTrace__CxE7ORPNkX9cb5SNfDQ2yPQ)(TFrame* f, NimStringV2& s) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	TFrame* it = f;
	NI i = ((NI) 0);
	NI total = ((NI) 0);
	{
		while (1) {
			NIM_BOOL T4_;
			T4_ = (NIM_BOOL)0;
			T4_ = !((it == NIM_NIL));
			if (!(T4_)) goto LA5_;
			T4_ = (i <= ((NI) 95));
			LA5_: ;
			if (!T4_) goto LA3;
			tempFrames__7nBYIr2UsDREpYylZK4fug[(i)- 0] = it;
			i += ((NI) 1);
			total += ((NI) 1);
			it = (*it).prev;
		} LA3: ;
	}
	TFrame* b = it;
	{
		while (1) {
			if (!!((it == NIM_NIL))) goto LA7;
			total += ((NI) 1);
			it = (*it).prev;
		} LA7: ;
	}
	NI skipped = ((NI) 0);
	{
		if (!(((NI) 128) < total)) goto LA10_;
{		skipped = (NI)((NI)((NI)(total - i) - ((NI) 32)) + ((NI) 1));
		{
			NI j;
			j = (NI)0;
			NI res = ((NI) 1);
			{
				while (1) {
					if (!(res <= skipped)) goto LA14;
					j = res;
					{
						if (!!((b == NIM_NIL))) goto LA17_;
{						b = (*b).prev;
}					}
					LA17_: ;
					res += ((NI) 1);
				} LA14: ;
			}
		}
		tempFrames__7nBYIr2UsDREpYylZK4fug[(i)- 0] = NIM_NIL;
		i += ((NI) 1);
}	}
	LA10_: ;
	{
		while (1) {
			NIM_BOOL T21_;
			T21_ = (NIM_BOOL)0;
			T21_ = !((b == NIM_NIL));
			if (!(T21_)) goto LA22_;
			T21_ = (i <= ((NI) 127));
			LA22_: ;
			if (!T21_) goto LA20;
			tempFrames__7nBYIr2UsDREpYylZK4fug[(i)- 0] = b;
			i += ((NI) 1);
			b = (*b).prev;
		} LA20: ;
	}
	{
		NI j_2;
		NI colontmp_;
		j_2 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(i - ((NI) 1));
		NI res_2 = colontmp_;
		{
			while (1) {
				if (!(((NI) 0) <= res_2)) goto LA25;
				j_2 = res_2;
				{
					NimStringV2 T30_;
					if (!(tempFrames__7nBYIr2UsDREpYylZK4fug[(j_2)- 0] == NIM_NIL)) goto LA28_;
{					prepareAdd(s, 1);
appendString(s, TM__Q5wkpxktOdTGvlSRo9bzt9aw_42);
					T30_.len = 0; T30_.p = NIM_NIL;
					T30_ = nimIntToStr(skipped);
					eqsink___aBBXmHFBEivKqERloP6zmA(colontmpD_, T30_);
					prepareAdd(s, colontmpD_.len + 0);
appendString(s, colontmpD_);
					prepareAdd(s, 20);
appendString(s, TM__Q5wkpxktOdTGvlSRo9bzt9aw_52);
}				}
				goto LA26_;
				LA28_: ;
				{
					NI oldLenX60gensym1735039_ = s.len;
					add__8FwY5enLGB0dFerO6Ny9caw(s, (*tempFrames__7nBYIr2UsDREpYylZK4fug[(j_2)- 0]).filename);
					{
						NimStringV2 T36_;
						if (!(((NI) 0) < (*tempFrames__7nBYIr2UsDREpYylZK4fug[(j_2)- 0]).line)) goto LA34_;
{						nimAddCharV1(s, 40);
						T36_.len = 0; T36_.p = NIM_NIL;
						T36_ = nimIntToStr((*tempFrames__7nBYIr2UsDREpYylZK4fug[(j_2)- 0]).line);
						eqsink___aBBXmHFBEivKqERloP6zmA(colontmpD__2, T36_);
						prepareAdd(s, colontmpD__2.len + 0);
appendString(s, colontmpD__2);
						nimAddCharV1(s, 41);
}					}
					LA34_: ;
					{
						NI kX60gensym1735040_;
						NI colontmp__2;
						kX60gensym1735040_ = (NI)0;
						colontmp__2 = (NI)0;
						colontmp__2 = ((((NI) 1) >= (NI)(((NI) 25) - (NI)(s.len - oldLenX60gensym1735039_))) ? ((NI) 1) : (NI)(((NI) 25) - (NI)(s.len - oldLenX60gensym1735039_)));
						NI res_3 = ((NI) 1);
						{
							while (1) {
								if (!(res_3 <= colontmp__2)) goto LA39;
								kX60gensym1735040_ = res_3;
								nimAddCharV1(s, 32);
								res_3 += ((NI) 1);
							} LA39: ;
						}
					}
					add__8FwY5enLGB0dFerO6Ny9caw(s, (*tempFrames__7nBYIr2UsDREpYylZK4fug[(j_2)- 0]).procname);
					prepareAdd(s, 1);
appendString(s, TM__Q5wkpxktOdTGvlSRo9bzt9aw_56);
				}
				LA26_: ;
				res_2 -= ((NI) 1);
			} LA25: ;
		}
	}
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(colontmpD__2);
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(colontmpD_);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rawWriteStackTrace__LYPY2vdF8PVrf1RSKEqgkA)(NimStringV2& s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;
{		prepareAdd(s, 29);
appendString(s, TM__Q5wkpxktOdTGvlSRo9bzt9aw_6);
}	}
	goto LA1_;
	LA3_: ;
	{
		prepareAdd(s, 34);
appendString(s, TM__Q5wkpxktOdTGvlSRo9bzt9aw_40);
		auxWriteStackTrace__CxE7ORPNkX9cb5SNfDQ2yPQ(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw, s);
	}
	LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toNimStr)(NCSTRING str, NI len) {
	NimStringV2 result;
	NI colontmpD_;
{	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	colontmpD_ = (NI)0;
	{
		if (!(len <= ((NI) 0))) goto LA3_;
{		chckNil((void*)(&result));
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		result.p = NIM_NIL;
}	}
	goto LA1_;
	LA3_: ;
	{
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_57;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_58;
		if (nimAddInt(len, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_57)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_57), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_58)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_58)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_58)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_58), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		void* T6_ = allocShared0Impl__1Sx5YIRdVWZ4weqfKjYzWA(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_58))));
		NimStrPayload* p = ((NimStrPayload*) (T6_));
		(*p).cap = len;
		{
			if (!(((NI) 0) < len)) goto LA9_;
{			if ((len) < ((NI) 0) || (len) > ((NI) 2147483647)){ raiseRangeErrorI(len, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*p).data[((NI) 0)]))), ((void*) (str)), ((NI) (len)));
}		}
		LA9_: ;
		chckNil((void*)(&result));
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		colontmpD_ = len;
		result.len = colontmpD_;
		result.p = p;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(size_t, nimCStrLen)(NCSTRING a) {
	size_t result;
	result = (size_t)0;
	result = strlen(a);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str) {
	NimStringV2 result;
	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	{
		if (!(((void*) (str)) == NIM_NIL)) goto LA3_;
{		result = toNimStr(str, ((NI) 0));
}	}
	goto LA1_;
	LA3_: ;
	{
		result = toNimStr(str, (str ? nimCStrLen(str) : 0));
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eq___rR9boD7urcxl7uyUtE46AOA(currException__9bVPeDJlYTi9bQApZpfH8wjg, (*currException__9bVPeDJlYTi9bQApZpfH8wjg).up);
}
static N_INLINE(void, rawWrite)(FILE* f, NCSTRING s) {
	int T1_ = fwrite(((void*) (s)), ((size_t) 1), ((size_t) ((s ? nimCStrLen(s) : 0))), f);
	(void)(T1_);
	int T2_ = fflush(f);
	(void)(T2_);
}
N_LIB_PRIVATE N_NIMCALL(void, writeToStdErr__a2kDfqdSc1eYf0ZCWOGinQ)(NCSTRING msg) {
	rawWrite(stderr, msg);
}
N_LIB_PRIVATE N_NIMCALL(void, showErrorMessage__zsORN9crdKxsL9cHrQcdHSMw)(NCSTRING data) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	NIM_BOOL toWrite = NIM_TRUE;
	{
		NimStringV2 T7_;
		if (!!((errorMessageWriter__ZXnv0JyrWe3HTd07wpSr7A == NIM_NIL))) goto LA4_;
{		T7_.len = 0; T7_.p = NIM_NIL;
		T7_ = cstrToNimstr(data);
		eqsink___aBBXmHFBEivKqERloP6zmA(colontmpD_, T7_);
		errorMessageWriter__ZXnv0JyrWe3HTd07wpSr7A(colontmpD_);
		toWrite = NIM_FALSE;
		if (NIM_UNLIKELY(*nimErr_)) {
			LA6_:;
			{
				*nimErr_ = NIM_FALSE;
				popCurrentException();
				LA9_:;
			}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
}	}
	LA4_: ;
	{
		if (!toWrite) goto LA13_;
{		writeToStdErr__a2kDfqdSc1eYf0ZCWOGinQ(data);
}	}
	LA13_: ;
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(colontmpD_);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		if (!(s.len == ((NI) 0))) goto LA3_;
{		result = "";
}	}
	goto LA1_;
	LA3_: ;
	{
		result = ((NCSTRING) ((*s.p).data));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, writeStackTrace__amVlU9ajqZ06ujoesRBHcDg)(void) {
	NimStringV2 s;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	s.len = 0; s.p = NIM_NIL;
	s = TM__Q5wkpxktOdTGvlSRo9bzt9aw_4;
	rawWriteStackTrace__LYPY2vdF8PVrf1RSKEqgkA(s);
	showErrorMessage__zsORN9crdKxsL9cHrQcdHSMw(nimToCStringConv(s));
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(s);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 T2_;
	NimStringV2 T3_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	writeStackTrace__amVlU9ajqZ06ujoesRBHcDg();
	T2_.len = 0; T2_.p = NIM_NIL;
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_ = nimIntToStr(((NI) 2000));
	eqsink___aBBXmHFBEivKqERloP6zmA(colontmpD_, T3_);
	T2_ = rawNewString(colontmpD_.len + 167);
appendString(T2_, TM__Q5wkpxktOdTGvlSRo9bzt9aw_60);
appendString(T2_, colontmpD_);
appendString(T2_, TM__Q5wkpxktOdTGvlSRo9bzt9aw_62);
	eqsink___aBBXmHFBEivKqERloP6zmA(colontmpD__2, T2_);
	showErrorMessage__zsORN9crdKxsL9cHrQcdHSMw(nimToCStringConv(colontmpD__2));
	exit(((NI) 1));
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(colontmpD__2);
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(colontmpD_);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;
{		(*s).calldepth = ((NI16) 0);
}	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA8_;
{		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
}	}
	LA8_: ;
}
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/arithmetics."
"nim");
	result = (NI)0;
	nimln_(437, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/arithmetics."
"nim");
	nimln_(441, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/arithmetics."
"nim");
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLast", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
{	result = (NIM_BOOL)0;
	nimln_(137, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	{
		if (!!((p == NIM_NIL))) goto LA3_;
{		nimln_(138, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
		nimln_(55, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
		NI T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 4));
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		nimln_(139, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
		{
			if (!((NI)((*cell).rc & ((NI) -8)) == ((NI) 0))) goto LA8_;
{			nimln_(140, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
			result = NIM_TRUE;
}		}
		goto LA6_;
		LA8_: ;
		{
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_63;
			nimln_(144, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
			if (nimSubInt((*cell).rc, ((NI) 8), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_63)) { raiseOverflow(); goto BeforeRet_;
};
			(*cell).rc = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_63);
		}
		LA6_: ;
}	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___SJcVq9aHUKEeQF6mKDkE6pw)(tyObject_OverflowError__Ss6DFlX5iSZpHRZDmP74bg& dest) {
	{
		NIM_BOOL T3_ = nimDecRefIsLast(dest.parent);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest.parent);
		dest.parent = NIM_NIL;
}	}
	LA4_: ;
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(dest.message);
	eqdestroy___4fQQqvAqifkWGVa4g39cI5A(dest.trace);
	{
		NIM_BOOL T8_ = nimDecRefIsLast(dest.up);
		if (!T8_) goto LA9_;
{		nimDestroyAndDispose(dest.up);
		dest.up = NIM_NIL;
}	}
	LA9_: ;
}
static N_INLINE(void, sysFatal__1rw9bzpRcCrBi6FIqHe7a4wsystem)(NimStringV2 message) {
	tyObject_OverflowError__Ss6DFlX5iSZpHRZDmP74bg* T2_;
	NimStringV2 blitTmp;
NIM_BOOL* nimErr_;
	nimfr_("sysFatal", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/fatal.nim");
{nimErr_ = nimErrorFlag();
	T2_ = (tyObject_OverflowError__Ss6DFlX5iSZpHRZDmP74bg*)0;
	T2_ = (tyObject_OverflowError__Ss6DFlX5iSZpHRZDmP74bg*) nimNewObj(sizeof(tyObject_OverflowError__Ss6DFlX5iSZpHRZDmP74bg));
	(*T2_).m_type = (&NTI__Ss6DFlX5iSZpHRZDmP74bg_);
	(*T2_).name = "OverflowError";
	nimln_(49, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/fatal.nim");
	blitTmp = message;
	message.len = 0; message.p = NIM_NIL;
	(*T2_).message = blitTmp;
	raiseExceptionEx((Exception*)T2_, "OverflowError", "sysFatal", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/fatal.nim", 49);
	goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(message);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	sysFatal__1rw9bzpRcCrBi6FIqHe7a4wsystem(TM__Q5wkpxktOdTGvlSRo9bzt9aw_65);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size) {
	void* result;
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_2;
	nimfr_("nimNewObj", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
{	result = (void*)0;
	nimln_(61, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	if (nimAddInt(size, ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_2)) { raiseOverflow(); goto BeforeRet_;
};
	NI s = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_2);
	nimln_(65, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	void* T1_ = malloc(((size_t) (((unsigned int) (s)))));
	void* orig = T1_;
	nimln_(66, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	if ((s) < ((NI) 0) || (s) > ((NI) 2147483647)){ raiseRangeErrorI(s, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	nimZeroMem(orig, ((NI) (s)));
	nimln_(67, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	nimln_(49, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/refs_v2.nim");
	NI T2_ = pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (orig)), ((NI) 4));
	result = ((void*) (T2_));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___p2qOs6FbMz4AMrZbQK62BQ)(tyObject_RangeError__8inKGns6i1OoXN9aLZwcSOw& dest) {
	{
		NIM_BOOL T3_ = nimDecRefIsLast(dest.parent);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest.parent);
		dest.parent = NIM_NIL;
}	}
	LA4_: ;
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(dest.message);
	eqdestroy___4fQQqvAqifkWGVa4g39cI5A(dest.trace);
	{
		NIM_BOOL T8_ = nimDecRefIsLast(dest.up);
		if (!T8_) goto LA9_;
{		nimDestroyAndDispose(dest.up);
		dest.up = NIM_NIL;
}	}
	LA9_: ;
}
static N_INLINE(void, sysFatal__UO7gyScsaKQMHY4DQ3daHgsystem)(NimStringV2 message) {
	tyObject_RangeError__8inKGns6i1OoXN9aLZwcSOw* T2_;
	NimStringV2 blitTmp;
NIM_BOOL* nimErr_;
	nimfr_("sysFatal", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/fatal.nim");
{nimErr_ = nimErrorFlag();
	T2_ = (tyObject_RangeError__8inKGns6i1OoXN9aLZwcSOw*)0;
	T2_ = (tyObject_RangeError__8inKGns6i1OoXN9aLZwcSOw*) nimNewObj(sizeof(tyObject_RangeError__8inKGns6i1OoXN9aLZwcSOw));
	(*T2_).m_type = (&NTI__8inKGns6i1OoXN9aLZwcSOw_);
	(*T2_).name = "RangeError";
	nimln_(49, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/fatal.nim");
	blitTmp = message;
	message.len = 0; message.p = NIM_NIL;
	(*T2_).message = blitTmp;
	raiseExceptionEx((Exception*)T2_, "RangeError", "sysFatal", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/fatal.nim", 49);
	goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(message);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimInt64ToStr)(NI64 x) {
	NimStringV2 result;
	nimfr_("nimInt64ToStr", "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
	result.len = 0; result.p = NIM_NIL;
	nimln_(284, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
	result = rawNewString(((NI) 32));
	nimln_(285, "/home/elcritch/.asdf/installs/nim/1.2.0/lib/system/strmantle.ni"
"m");
	addInt__mftMOxbyu0h4yByfs3sqjA(result, x);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 colontmpD__3;
	NimStringV2 T2_;
	NimStringV2 T3_;
	NimStringV2 T4_;
	NimStringV2 T5_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	T2_.len = 0; T2_.p = NIM_NIL;
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_ = nimInt64ToStr(i);
	eqsink___aBBXmHFBEivKqERloP6zmA(colontmpD_, T3_);
	T4_.len = 0; T4_.p = NIM_NIL;
	T4_ = nimInt64ToStr(a);
	eqsink___aBBXmHFBEivKqERloP6zmA(colontmpD__2, T4_);
	T5_.len = 0; T5_.p = NIM_NIL;
	T5_ = nimInt64ToStr(b);
	eqsink___aBBXmHFBEivKqERloP6zmA(colontmpD__3, T5_);
	T2_ = rawNewString(colontmpD_.len + colontmpD__2.len + colontmpD__3.len + 31);
appendString(T2_, TM__Q5wkpxktOdTGvlSRo9bzt9aw_67);
appendString(T2_, colontmpD_);
appendString(T2_, TM__Q5wkpxktOdTGvlSRo9bzt9aw_69);
appendString(T2_, colontmpD__2);
appendString(T2_, TM__Q5wkpxktOdTGvlSRo9bzt9aw_71);
appendString(T2_, colontmpD__3);
	sysFatal__UO7gyScsaKQMHY4DQ3daHgsystem(T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(colontmpD__3);
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(colontmpD__2);
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(colontmpD_);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, reportUnhandledError__na8C8pUZ9cLQWVwk35l5vfw_2)(Exception* e) {
	{
		if (!!((unhandledExceptionHook__RJpSsXsRUH8ochbXTEhRIw == NIM_NIL))) goto LA3_;
{		unhandledExceptionHook__RJpSsXsRUH8ochbXTEhRIw(e);
}	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimInErrorMode__759bT87luu8XGcbkw13FUjA;
		if (!(T3_)) goto LA4_;
		T3_ = !((currException__9bVPeDJlYTi9bQApZpfH8wjg == NIM_NIL));
		LA4_: ;
		if (!T3_) goto LA5_;
{		reportUnhandledError__na8C8pUZ9cLQWVwk35l5vfw_2(currException__9bVPeDJlYTi9bQApZpfH8wjg);
		eqsink___rR9boD7urcxl7uyUtE46AOA_2(currException__9bVPeDJlYTi9bQApZpfH8wjg, NIM_NIL);
		exit(((NI) 1));
}	}
	LA5_: ;
}
static N_INLINE(void, initStackBottomWith)(void* locals) {
}
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void) {
{
	initStackBottom();
}
}

N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void) {
NTI__vASt1Zy2CLWqyBeLxcXqow_.destructor = (void*)eqdestroy___CiaBzGuSuzPVhX0vLVmlsg; NTI__vASt1Zy2CLWqyBeLxcXqow_.size = sizeof(tyObject_DivByZeroError__vASt1Zy2CLWqyBeLxcXqow);
NTI__vASt1Zy2CLWqyBeLxcXqow_.name = "|DivByZeroError|ArithmeticError|Defect|Exception|RootObj|";
NTI__vASt1Zy2CLWqyBeLxcXqow_.traceImpl = (void*)NIM_NIL;
NTI__vASt1Zy2CLWqyBeLxcXqow_.disposeImpl = (void*)NIM_NIL;
NTI__GOcOTSJVFwA9bjh66gBCclQ_.destructor = (void*)eqdestroy___sS6ejz4UvAmG5PeEn1axqQ; NTI__GOcOTSJVFwA9bjh66gBCclQ_.size = sizeof(tyObject_NilAccessError__GOcOTSJVFwA9bjh66gBCclQ);
NTI__GOcOTSJVFwA9bjh66gBCclQ_.name = "|NilAccessError|Defect|Exception|RootObj|";
NTI__GOcOTSJVFwA9bjh66gBCclQ_.traceImpl = (void*)NIM_NIL;
NTI__GOcOTSJVFwA9bjh66gBCclQ_.disposeImpl = (void*)NIM_NIL;
NTI__Ss6DFlX5iSZpHRZDmP74bg_.destructor = (void*)eqdestroy___SJcVq9aHUKEeQF6mKDkE6pw; NTI__Ss6DFlX5iSZpHRZDmP74bg_.size = sizeof(tyObject_OverflowError__Ss6DFlX5iSZpHRZDmP74bg);
NTI__Ss6DFlX5iSZpHRZDmP74bg_.name = "|OverflowError|ArithmeticError|Defect|Exception|RootObj|";
NTI__Ss6DFlX5iSZpHRZDmP74bg_.traceImpl = (void*)NIM_NIL;
NTI__Ss6DFlX5iSZpHRZDmP74bg_.disposeImpl = (void*)NIM_NIL;
NTI__8inKGns6i1OoXN9aLZwcSOw_.destructor = (void*)eqdestroy___p2qOs6FbMz4AMrZbQK62BQ; NTI__8inKGns6i1OoXN9aLZwcSOw_.size = sizeof(tyObject_RangeError__8inKGns6i1OoXN9aLZwcSOw);
NTI__8inKGns6i1OoXN9aLZwcSOw_.name = "|RangeError|Defect|Exception|RootObj|";
NTI__8inKGns6i1OoXN9aLZwcSOw_.traceImpl = (void*)NIM_NIL;
NTI__8inKGns6i1OoXN9aLZwcSOw_.disposeImpl = (void*)NIM_NIL;
}

